site_name: uCA Documentation
site_dir: site

theme:
  name: material
  font: false
  features:
    - navigation.sections # 하위 메뉴를 묶어줌
    - navigation.top # 위로가기 버튼
  palette:
    - scheme: slate
      primary: black
      accent: green            
      toggle:
        icon: material/weather-night
        name: 라이트 모드로 전환
    - scheme: default
      primary: white
      accent: green
      toggle:
        icon: material/weather-sunny
        name: 다크 모드로 전환

extra_css:
  - stylesheets/custom.css

nav:
  - HOME: index.md
  - Architecture: 
      - Overview: Architecture/index.md 
      - ISA Spec: Architecture/v001/v001_isa.md
  - Devices:
      - KV260: Devices/kv260.md
  - Drivers:
      - API: Drivers/API.md
  - Archive (Experimental):
      - v001 Overview: archive/experimental_v001/index.md
      - v001 Architecture: archive/experimental_v001/Architecture/v001_architecture.md
      - v001 ISA: archive/experimental_v001/Drivers/ISA.md
      - v001 ISA Sheet: archive/experimental_v001/Drivers/ISA_Spreadsheet.md
      - v001 API: archive/experimental_v001/Drivers/v001_API.md
      - v001 Agents: archive/experimental_v001/agents.md