site_name: uCA documentation
site_dir: site

theme:
  name: material
  font: false
  features:
    - navigation.tabs          # 상단바에 폴더(Architecture 등) 띄우기
    - navigation.expand        # 왼쪽 사이드바 접기/펼치기 활성화
    - navigation.top
  palette:
    # 다크 모드
    - scheme: slate
      primary: black
      accent: green            # 안드로이드 메인 컬러 적용
      toggle:
        icon: material/weather-night
        name: 라이트 모드로 전환
    # 라이트 모드
    - scheme: default
      primary: white
      accent: green
      toggle:
        icon: material/weather-sunny
        name: 다크 모드로 전환

extra_css:
  - stylesheets/custom.css

# [핵심] 이렇게 들여쓰기를 해야 상단=폴더, 왼쪽=문서 이름이 돼!
nav:
  - HOME: index.md
  - Architecture: 
      - Overview: Architecture/Architecture.md
      # 다른 문서가 생기면 여기에 계속 추가하면 됨
  - Devices: 
      - Overview: Devices/Devices.md
  - Drivers: 
      - Overview: Drivers/Drivers.md