site_name: uCA Documentation
site_dir: site

theme:
  name: material
  font: false
  features:
    - navigation.tabs # 메뉴를 상단으로 올림
    - navigation.sections # 하위 메뉴를 묶어줌
    - navigation.top # 위로가기 버튼
  palette:
    - scheme: slate
      primary: black
      accent: green            
      toggle:
        icon: material/weather-night
        name: 라이트 모드로 전환
    - scheme: default
      primary: white
      accent: green
      toggle:
        icon: material/weather-sunny
        name: 다크 모드로 전환

extra_css:
  - stylesheets/custom.css

nav:
  - HOME: index.md
  - Architecture: 
      - Overview: Architecture/index.md 
      - ISA Spec: Architecture/v001/v001_isa.md
  - Devices:
      - KV260: Devices/kv260.md
  - Drivers:
      - API: Drivers/API.md